apiVersion: v1
items:
- apiVersion: v1
  data:
    vault.hcl: |
      storage "consul" {
       address = "127.0.0.1:8500"
       path = "vault/"
       }
      listener "tcp" {
        address = "0.0.0.0:8200"
        tls_disable = "true"
      }
      disable_mlock="true"
      disable_cache="true"
      ui = "true"

      max_least_ttl="10h"
      default_least_ttl="10h"
      raw_storage_endpoint=true
      cluster_name="mycompany-vault"
  kind: ConfigMap
  metadata:
    name: vault
    namespace: vault-deploy
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
