apiVersion: v1
items:
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2019-03-19T13:46:30Z
    name: admin
    namespace: vault-deploy
    resourceVersion: "250030"
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/admin
    uid: 6660966b-4a4d-11e9-8657-005056bf8718
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ocadmin
  userNames:
  - ocadmin
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows deploymentconfigs in this namespace to rollout
        pods in this namespace.  It is auto-managed by a controller; remove subjects
        to disable.
    creationTimestamp: 2019-03-19T13:46:30Z
    name: system:deployers
    namespace: vault-deploy
    resourceVersion: "250026"
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/system%3Adeployers
    uid: 665e6709-4a4d-11e9-8657-005056bf8718
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: vault-deploy
  userNames:
  - system:serviceaccount:vault-deploy:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows builds in this namespace to push images to
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    creationTimestamp: 2019-03-19T13:46:30Z
    name: system:image-builders
    namespace: vault-deploy
    resourceVersion: "250022"
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/system%3Aimage-builders
    uid: 665cceea-4a4d-11e9-8657-005056bf8718
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: vault-deploy
  userNames:
  - system:serviceaccount:vault-deploy:builder
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:vault-deploy
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows all pods in this namespace to pull images from
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    creationTimestamp: 2019-03-19T13:46:30Z
    name: system:image-pullers
    namespace: vault-deploy
    resourceVersion: "250020"
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/system%3Aimage-pullers
    uid: 665ac36c-4a4d-11e9-8657-005056bf8718
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:vault-deploy
  userNames: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
