apiVersion: v1
items:
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: admin
    namespace: vault-deploy
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/admin
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ocadmin
  userNames:
  - ocadmin
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows deploymentconfigs in this namespace to rollout
        pods in this namespace.  It is auto-managed by a controller; remove subjects
        to disable.
    name: system:deployers
    namespace: vault-deploy
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/system%3Adeployers
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: vault-deploy
  userNames:
  - system:serviceaccount:vault-deploy:deployer
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows builds in this namespace to push images to
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    name: system:image-builders
    namespace: vault-deploy
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/system%3Aimage-builders
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: vault-deploy
  userNames:
  - system:serviceaccount:vault-deploy:builder
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - system:serviceaccounts:vault-deploy
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/description: Allows all pods in this namespace to pull images from
        this namespace.  It is auto-managed by a controller; remove subjects to disable.
    name: system:image-pullers
    namespace: vault-deploy
    selfLink: /apis/authorization.openshift.io/v1/namespaces/vault-deploy/rolebindings/system%3Aimage-pullers
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:vault-deploy
  userNames: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
