apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-mjmsf
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2019-03-19T13:46:30Z
    name: builder
    namespace: vault-deploy
    resourceVersion: "250048"
    selfLink: /api/v1/namespaces/vault-deploy/serviceaccounts/builder
    uid: 665d9aa4-4a4d-11e9-8657-005056bf8718
  secrets:
  - name: builder-token-jwwkd
  - name: builder-dockercfg-mjmsf
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-jtgxj
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2019-03-19T13:46:30Z
    name: default
    namespace: vault-deploy
    resourceVersion: "250047"
    selfLink: /api/v1/namespaces/vault-deploy/serviceaccounts/default
    uid: 665cdc33-4a4d-11e9-8657-005056bf8718
  secrets:
  - name: default-token-wzlxf
  - name: default-dockercfg-jtgxj
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-nvcr6
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2019-03-19T13:46:30Z
    name: deployer
    namespace: vault-deploy
    resourceVersion: "250049"
    selfLink: /api/v1/namespaces/vault-deploy/serviceaccounts/deployer
    uid: 665f5aca-4a4d-11e9-8657-005056bf8718
  secrets:
  - name: deployer-token-h287t
  - name: deployer-dockercfg-nvcr6
- apiVersion: v1
  imagePullSecrets:
  - name: privilegeduser-dockercfg-h6zg8
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2019-03-19T13:48:40Z
    name: privilegeduser
    namespace: vault-deploy
    resourceVersion: "250304"
    selfLink: /api/v1/namespaces/vault-deploy/serviceaccounts/privilegeduser
    uid: b3f528f3-4a4d-11e9-8657-005056bf8718
  secrets:
  - name: privilegeduser-dockercfg-h6zg8
  - name: privilegeduser-token-547cn
- apiVersion: v1
  imagePullSecrets:
  - name: vault-auth-dockercfg-fqdsz
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2019-03-19T14:23:19Z
    name: vault-auth
    namespace: vault-deploy
    resourceVersion: "254275"
    selfLink: /api/v1/namespaces/vault-deploy/serviceaccounts/vault-auth
    uid: 8b6b66ed-4a52-11e9-8657-005056bf8718
  secrets:
  - name: vault-auth-token-58zmf
  - name: vault-auth-dockercfg-fqdsz
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
